// Mapeo de código de piloto → ruta local en /public/drivers/
// Fotos oficiales de media.formula1.com (parrilla 2026 + ausentes con su última temporada)
export const DRIVER_PHOTOS: Record<string, string> = {
  ALB: "/drivers/2026-ALB.webp",
  ALO: "/drivers/2026-ALO.webp",
  ANT: "/drivers/2026-ANT.webp",
  BEA: "/drivers/2026-BEA.webp",
  BOR: "/drivers/2026-BOR.webp",
  BOT: "/drivers/2026-BOT.webp",
  COL: "/drivers/2026-COL.webp",
  GAS: "/drivers/2026-GAS.webp",
  HAD: "/drivers/2026-HAD.webp",
  HAM: "/drivers/2026-HAM.webp",
  HUL: "/drivers/2026-HUL.webp",
  LAW: "/drivers/2026-LAW.webp",
  LEC: "/drivers/2026-LEC.webp",
  LIN: "/drivers/2026-LIN.webp",
  NOR: "/drivers/2026-NOR.webp",
  OCO: "/drivers/2026-OCO.webp",
  PER: "/drivers/2026-PER.webp",
  PIA: "/drivers/2026-PIA.webp",
  RUS: "/drivers/2026-RUS.webp",
  SAI: "/drivers/2026-SAI.webp",
  STR: "/drivers/2026-STR.webp",
  VER: "/drivers/2026-VER.webp",
  DOO: "/drivers/2025-DOO.webp",
  TSU: "/drivers/2025-TSU.webp",
};

// Nacionalidad (Jolpica) → código de país de 3 letras (estilo F1/COI)
export const NATIONALITY_CODE: Record<string, string> = {
  Dutch: "NED",
  British: "GBR",
  Monegasque: "MON",
  Spanish: "ESP",
  Australian: "AUS",
  Mexican: "MEX",
  Finnish: "FIN",
  German: "GER",
  French: "FRA",
  Danish: "DEN",
  Canadian: "CAN",
  Thai: "THA",
  Japanese: "JPN",
  American: "USA",
  Chinese: "CHN",
  Italian: "ITA",
  Brazilian: "BRA",
  Argentine: "ARG",
  Argentinian: "ARG",
  Austrian: "AUT",
  Swiss: "SUI",
  "New Zealander": "NZL",
  Belgian: "BEL",
  Russian: "RUS",
  Polish: "POL",
};

// Mapeo de constructorId (Jolpica) → coche 2026 oficial en /public/cars/
export const CAR_IMAGES: Record<string, string> = {
  red_bull:     "/cars/2026-red_bull.webp",
  mercedes:     "/cars/2026-mercedes.webp",
  ferrari:      "/cars/2026-ferrari.webp",
  mclaren:      "/cars/2026-mclaren.webp",
  aston_martin: "/cars/2026-aston_martin.webp",
  alpine:       "/cars/2026-alpine.webp",
  williams:     "/cars/2026-williams.webp",
  rb:           "/cars/2026-rb.webp",
  racing_bulls: "/cars/2026-rb.webp",
  haas:         "/cars/2026-haas.webp",
  audi:         "/cars/2026-audi.webp",
  cadillac:     "/cars/2026-cadillac.webp",
};

// Mapeo de constructorId (Jolpica) → ruta local en /public/teams/
export const TEAM_LOGOS: Record<string, string> = {
  red_bull:     "/teams/red-bull.png",
  mercedes:     "/teams/mercedes.png",
  ferrari:      "/teams/ferrari.png",
  mclaren:      "/teams/mclaren.png",
  aston_martin: "/teams/aston-martin.png",
  alpine:       "/teams/alpine.png",
  williams:     "/teams/williams.png",
  rb:           "/teams/visa-red.png",
  racing_bulls: "/teams/visa-red.png",
  kick_sauber:  "/teams/kick.png",
  sauber:       "/teams/kick.png",
  haas:         "/teams/haas.png",
  audi:         "/teams/audi.png",
  cadillac:     "/teams/cadillac.png",
};
